PROJECT02/boards/urls.py
from django.urls import path, include
from . import views

app_name = 'boards'

urlpatterns = [
    
    path('<int:board_pk>/comments/<int:comment_pk>/delete/',views.comments_delete, name = 'comments_delete'),
    path('<int:board_pk>/comments/',views.comments_create, name = 'comments_create'),
    path('<int:board_pk>/delete/',views.delete, name = 'delete'),
    path('<int:board_pk>/edit/',views.edit, name = 'edit'),
    path('<int:board_pk>/',views.detail,name = 'detail'),
    path('new/',views.new, name = 'new'),
    path('',views.index, name = 'index'),
]

PROJECT02/crud/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('boards/', include('boards.urls')),
    path('admin/', admin.site.urls),
]

TUTO03/TUTO03/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('boards/', include('boards.urls')),
    path('admin/', admin.site.urls),
]

TUTO03/boards/urls.py
from django.urls import path,include
from . import views
app_name = 'boards'
urlpatterns = [
    path('edit/<int:boards_pk>',views.edit, name='edit'),
    path('detail/<int:boards_pk>/delete',views.delete, name='delete'),
    path('detail/<int:boards_pk>',views.detail, name='detail'),
    path('new/',views.new, name='new'),
    path('',views.index, name='index'),
]

crud/urls.py
from django.contrib import admin
from django.urls import path

urlpatterns = [
    path('admin/', admin.site.urls),
]

PROJECT02/boards/models.py
from django.db import models

# Create your models here.

class Board(models.Model):
    title = models.CharField(max_length=10) # length limit
    content = models.TextField() # it doesn't have length limits
    created_at = models.DateField(auto_now_add=True)
    updated_at = models.DateField(auto_now=True)
    # updated_at = models.DateField()
    def __str__(self):
        return f'{self.id} - {self.title} : {self.content}'

class Comment(models.Model):
    content = models.CharField(max_length=200)
    created_at = models.DateField(auto_now_add=True)
    updated_at = models.DateField(auto_now=True)
    board = models.ForeignKey(Board, on_delete=models.CASCADE)

    def __str__(self):
        return f'<Board({self.board_id}): Comment({self.id})> -{self.content}'

# Board.objects.all()
# Board.objects.create(title='third',content='django')
# board.full_clean() method

# board.comment_set.all(); comments that the board has

PROJECT1/board/models.py
from django.db import models

# Create your models here.

class Candidate(models.Model):
    name = models.CharField(max_length=10)
    introduction = models.TextField()
    area = models.CharField(max_length=15)
    party_number = models.IntegerField(default=0)

TUTO03/boards/models.py
from django.db import models

# Create your models here.

class Board(models.Model):
    title = models.CharField(max_length=10)
    content = models.TextField()
    created_at = models.DateField(auto_now_add=True)
    updated_at = models.DateField(auto_now=True)

PROJECT02/boards/views.py
from django.shortcuts import redirect, render
from .models import Board,Comment
def index(request):

    # boards = Board.objects.order_by('-id') # method 1
    boards = Board.objects.all()[::-1]

    return render(request,'boards/index.html',{'boards':boards})

def new(request):
    if request.method =='POST':
        title= request.POST.get('title')
        content= request.POST.get('content')

        board = Board(title=title,content=content)
        board.save()

        return redirect('boards:detail',board.pk)
    else:
        return render(request,'boards/new.html')

def detail(request,board_pk):
    board = Board.objects.get(pk=board_pk)
    comments = board.comment_set.all()
    return render(request,'boards/detail.html',{'board':board,'comments':comments})
# Create your views here.


def delete(request,board_pk):
    board = Board.objects.get(pk=board_pk)
    
    if request.method=="POST":
        board.delete()
        return redirect('boards:index')
    else:
        return redirect('boards:detail',board.pk)

def edit(request,board_pk):
    
    board = Board.objects.get(pk=board_pk)
    if request.method=='POST':
        board.title = request.POST.get('title')
        board.content = request.POST.get('content')
        board.save()
        return redirect('boards:detail',board.pk)
    else:
        return render(request,'boards/edit.html', {'board':board})

def comments_create(request,board_pk):
    board = Board.objects.get(pk = board_pk)
    if request.method =='POST':
        comment = Comment()
        # form 에서 보낸 댓글 정보를 저장한다.
        comment.content = request.POST.get('content')
        comment.board = board
        comment.save()
        return redirect('boards:detail',board.pk)
    else:
        return redirect('boards:detail', board.pk)

def comments_delete(request,board_pk,comment_pk):
    comment = Comment.objects.get(pk=comment_pk)
    if request.method == 'POST':
        comment.delete()
        return redirect('boards:detail', board_pk)
    else:
        return redirect('boards:detail', board_pk)

PROJECT1/board/views.py
from django.shortcuts import render
from django.http import HttpResponse


# Create your views here.

def index(request):
    return render(request,'board/index.html')


def create(request):
    return render(request,'board/create.html')

TUTO03/boards/views.py
from django.shortcuts import render,redirect
from .models import Board
# Create your views here.

def index(request):
    boards= Board.objects.all()

    return render(request,'boards/index.html',{'boards':boards})


def new(request):
    if request.method =='POST':
        board = Board()
        board.title = request.POST.get('title')
        board.content = request.POST.get('content')
        board.save()
        return redirect('boards:detail',board.pk)

    else:
        return render(request,'boards/new.html')

def detail(request,boards_pk):
    board= Board.objects.get(pk=boards_pk)
    return render(request,'boards/detail.html',{'board':board})

def delete(request,boards_pk):
    board = Board.objects.get(pk=boards_pk)
    board.delete()
    return redirect('boards:index')

def edit(request,boards_pk):
    board = Board.objects.get(pk=boards_pk)
    if request.method == "POST":
        board.title = request.POST.get('title')
        board.content = request.POST.get('content')
        board.save()
        return redirect('boards:detail',board.pk)
    else:
        return render(request,'boards/edit.html',{'board':board})
    

PROJECT02/boards/templates/boards/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">

    <title>{%block title%}{%endblock%}</title>
    {%block css%}{%endblock%}
</head>
<body>
    <h1 class='text-center'>django try</h1>
    <hr>
    <div class="container">
        {%block body%}
        {%endblock%}
    </div>
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
</body>
</html>

PROJECT02/boards/templates/boards/create.html
{%extends 'boards/base.html' %}

{%block body%}
<h1 class ='text-center'> Success</h1>
{%endblock%}

PROJECT02/boards/templates/boards/detail.html
{%extends 'boards/base.html'%}

{%block body%}
    <h1 class= 'text-center'> DETAIL </h1>
    <h2>{{board.pk}}th </h2>
    <hr>
    <p>title :{{board.title}}</p>
    <p>content :{{board.content}}</p>
    <p>created at : {{board.created_at}}</p>
    <p>updated at : {{board.updated_at}}</p>
    <p><b>comments list / the number of comments : {{comments| length}}</b></p>
    {%for comment in comments %}
        <li> {{comment.content}}</li>
        <form action="{%url 'boards:comments_delete' board.pk comment.pk %}" method="POST">
            {%csrf_token%}
            <input type="submit" value="Delete comment">
        </form>
        <hr>
    {%empty%}
        <p>has no comment</p> 
    {%endfor%}
    <hr>
    <form action="{% url 'boards:comments_create' board.pk%}" method="POST">
        {%csrf_token%}
        Comment : <input type="text" name = "content"/>
        <input type="submit" value="Write">        
    </form>

    <!-- <a href="{% url 'boards:delete' board.pk%}">delete</a><br> -->
    <form action='{%url 'boards:delete' board.pk%}' method="POST">
        {%csrf_token%}
        <input type="submit" value ="Delete">
    </form>
    <a href="{% url 'boards:index' %}"> to main</a><br>
    <a href="{% url 'boards:edit' board.pk%}"> edit </a><br>
{%endblock%}

PROJECT02/boards/templates/boards/edit.html
{%extends 'boards/base.html'%}

{%block body%}
<h1 class='text-center'> NEW </h1>
<form action="" method="POST">
    {% csrf_token %}
    <label for="title">Title</label><br>
    <input type="text" name="title" id='title' value = '{{board.title}}'/><br>
    <label for="content">Content</label><br>
    <textarea name="content" id="content" cols="30" rows="10">{{board.content}}</textarea><br>
    <input type="submit"value="Submit">
</form>
{%endblock%}

PROJECT02/boards/templates/boards/index.html
{% extends 'boards/base.html' %}

{% block body%}
    <h1 class = 'text-center'>Boards</h1>
    <hr>
    {% for board in boards %}
        <p>number : {{board.pk}}</p>
        <p>title : {{board.title}}</p>
        <a href="{% url 'boards:detail' board.pk%}"> click </a>
        <hr>
    {%endfor%}
    <a href="{% url 'boards:new'%}">write new thing</a>
{% endblock%}

PROJECT02/boards/templates/boards/new.html
{%extends 'boards/base.html' %}

{%block body%}
    <h1 class='text-center'> NEW </h1>
    <form action="" method="POST">
        {% csrf_token %}
        <label for="title">Title</label><br>
        <input type="text" name="title" id='title'/><br>
        <label for="content">Content</label><br>
        <textarea name="content" id="content" cols="30" rows="10"></textarea><br>
        <input type="submit"value="Submit">
    </form>
{%endblock %}